import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { CardanoWallet,Factory, ProtocolParameters, protocolParametersQuery } from 'cardano-wallet-tx'
import { useContext, useEffect, useState } from 'react'
import ConfigContext from '../utils/ConfigContext'

const Home: NextPage = () => {
  const [cardanoWallet, setCardano] = useState<CardanoWallet | undefined>(undefined)
  const [config, _] = useContext(ConfigContext)
  const [pParams, setPParams] = useState<ProtocolParameters | undefined>(undefined)
  const CardanoSerializationLib = new Factory()
  const load = async () => {
    const pp = await protocolParametersQuery(config)
    console.log('loaded: ' + JSON.stringify(pp))
    setPParams(pp)
  }
  useEffect(() => {
    let isMounted = true

    CardanoSerializationLib.load().then((instance: CardanoWallet | undefined) => {
        isMounted && setCardano(instance)
        console.log('cardanoWallet')
        console.log(instance)
    })

    return () => {
        isMounted = false
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        { cardanoWallet ? <button onClick={load}>Click</button> : <button disabled>Click</button> }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
